package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/Skund404/commons-tool/internal/indexer"
)

// Drafts live as JSON files in <corpusRoot>/.drafts/<id>.json. The directory
// is gitignored per the v1 spec, so drafts never leak into commits unless the
// maintainer explicitly stages them via the stage endpoint, which projects
// the draft into primitives/<kind>/<slug>.json and removes the draft file.
//
// Each draft stores the UI-shape body (mutable, no validation required) plus
// envelope metadata (created/modified timestamps). This avoids re-projecting
// on every Save while the user types.

const draftsSubdir = ".drafts"

type draftEnvelope struct {
	ID         string         `json:"id"`
	Slug       string         `json:"slug,omitempty"` // mirror of body.slug for fast list
	Kind       string         `json:"kind,omitempty"`
	Title      string         `json:"title,omitempty"`
	CreatedAt  time.Time      `json:"created_at"`
	ModifiedAt time.Time      `json:"modified_at"`
	Body       map[string]any `json:"body"`
}

func (s *Server) draftsDir() string {
	return filepath.Join(s.CorpusRoot, draftsSubdir)
}

func (s *Server) ensureDraftsDir() error {
	dir := s.draftsDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	// Always also ensure .gitignore inside .drafts/ so drafts directory is
	// never tracked even if the user forgets to add it at the repo root.
	gi := filepath.Join(dir, ".gitignore")
	if _, err := os.Stat(gi); os.IsNotExist(err) {
		_ = os.WriteFile(gi, []byte("# Auto-generated by commons; drafts are local-only.\n*\n!.gitignore\n"), 0o644)
	}
	return nil
}

func (s *Server) draftPath(id string) string {
	safe := filepath.Base(id) // disallow traversal
	return filepath.Join(s.draftsDir(), safe+".json")
}

// readDraft loads a single envelope by id, or (nil, nil) if absent.
func (s *Server) readDraft(id string) (*draftEnvelope, error) {
	b, err := os.ReadFile(s.draftPath(id))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var env draftEnvelope
	if err := json.Unmarshal(b, &env); err != nil {
		return nil, err
	}
	return &env, nil
}

func (s *Server) writeDraft(env *draftEnvelope) error {
	if err := s.ensureDraftsDir(); err != nil {
		return err
	}
	env.ModifiedAt = time.Now().UTC()
	return atomicWriteJSON(s.draftPath(env.ID), env)
}

// newDraftID assembles a sortable id from the current timestamp plus a short
// random suffix. Avoids the UUID dependency footprint; collision odds are
// negligible for a single-user tool.
func newDraftID() string {
	now := time.Now().UTC()
	return fmt.Sprintf("draft-%s-%x", now.Format("20060102-150405"), now.UnixNano()%0xffff)
}

// ─────────── handlers ───────────

// handleDraftCreate handles POST /api/drafts/primitives.
// Body is the initial UI-shape body (may be partial — drafts are mutable).
func (s *Server) handleDraftCreate(w http.ResponseWriter, r *http.Request) {
	var body map[string]any
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil && err.Error() != "EOF" {
		writeError(w, 400, err.Error())
		return
	}
	if body == nil {
		body = map[string]any{}
	}
	env := &draftEnvelope{
		ID:        newDraftID(),
		CreatedAt: time.Now().UTC(),
		Body:      body,
	}
	env.Slug, _ = body["slug"].(string)
	env.Kind, _ = body["kind"].(string)
	env.Title, _ = body["name"].(string)
	if err := s.writeDraft(env); err != nil {
		writeError(w, 500, err.Error())
		return
	}
	writeJSON(w, http.StatusCreated, env)
}

// handleDraftList handles GET /api/drafts/primitives. Returns envelopes with
// metadata but not full body (kept lightweight for the list view).
func (s *Server) handleDraftList(w http.ResponseWriter, r *http.Request) {
	if err := s.ensureDraftsDir(); err != nil {
		writeError(w, 500, err.Error())
		return
	}
	entries, err := os.ReadDir(s.draftsDir())
	if err != nil {
		writeError(w, 500, err.Error())
		return
	}
	type summary struct {
		ID         string    `json:"id"`
		Slug       string    `json:"slug"`
		Kind       string    `json:"kind"`
		Title      string    `json:"title"`
		CreatedAt  time.Time `json:"created_at"`
		ModifiedAt time.Time `json:"modified_at"`
	}
	out := []summary{}
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".json" {
			continue
		}
		id := strings.TrimSuffix(e.Name(), ".json")
		env, err := s.readDraft(id)
		if err != nil || env == nil {
			continue
		}
		out = append(out, summary{
			ID:         env.ID,
			Slug:       env.Slug,
			Kind:       env.Kind,
			Title:      env.Title,
			CreatedAt:  env.CreatedAt,
			ModifiedAt: env.ModifiedAt,
		})
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].ModifiedAt.After(out[j].ModifiedAt) })
	writeJSON(w, 200, out)
}

// handleDraftGet handles GET /api/drafts/primitives/{id}.
func (s *Server) handleDraftGet(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	env, err := s.readDraft(id)
	if err != nil {
		writeError(w, 500, err.Error())
		return
	}
	if env == nil {
		writeError(w, 404, "draft not found")
		return
	}
	writeJSON(w, 200, env)
}

// handleDraftUpdate handles PUT /api/drafts/primitives/{id}. Body is the
// full UI-shape body to replace the draft body.
func (s *Server) handleDraftUpdate(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	env, err := s.readDraft(id)
	if err != nil {
		writeError(w, 500, err.Error())
		return
	}
	if env == nil {
		writeError(w, 404, "draft not found")
		return
	}
	var body map[string]any
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		writeError(w, 400, err.Error())
		return
	}
	env.Body = body
	env.Slug, _ = body["slug"].(string)
	env.Kind, _ = body["kind"].(string)
	env.Title, _ = body["name"].(string)
	if err := s.writeDraft(env); err != nil {
		writeError(w, 500, err.Error())
		return
	}
	writeJSON(w, 200, env)
}

// handleDraftDelete handles DELETE /api/drafts/primitives/{id}.
func (s *Server) handleDraftDelete(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if err := os.Remove(s.draftPath(id)); err != nil {
		if os.IsNotExist(err) {
			writeError(w, 404, "draft not found")
			return
		}
		writeError(w, 500, err.Error())
		return
	}
	writeJSON(w, 200, map[string]any{"ok": true, "deleted": id})
}

// handleDraftValidate handles POST /api/drafts/primitives/{id}/validate. Runs
// every gate the write pipeline applies (except the file write) and returns
// the structured result — never modifies disk state.
func (s *Server) handleDraftValidate(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	env, err := s.readDraft(id)
	if err != nil {
		writeError(w, 500, err.Error())
		return
	}
	if env == nil {
		writeError(w, 404, "draft not found")
		return
	}

	corpus, err := indexer.LoadCorpus(s.CorpusRoot, "primitives")
	if err != nil {
		writeError(w, 500, err.Error())
		return
	}

	specDoc, resErrs := projectPrimitiveFromUI(uiProjectionInput{
		UI:      env.Body,
		Corpus:  corpus,
		NowDate: time.Now().UTC().Format("2006-01-02"),
	})

	type fieldErr struct {
		Field   string `json:"field"`
		Sev     string `json:"sev"` // "reject" | "warn"
		Message string `json:"message"`
	}
	out := struct {
		OK     bool       `json:"ok"`
		Errors []fieldErr `json:"errors,omitempty"`
	}{OK: true}

	for _, e := range resErrs {
		out.OK = false
		out.Errors = append(out.Errors, fieldErr{
			Field: e.Field, Sev: "reject", Message: e.Reason,
		})
	}

	if specDoc != nil {
		// Inject a placeholder hash so the content_hash-required gate doesn't
		// trip; we recompute it for real at stage time. The placeholder is
		// well-formed (64 hex digits) so the format check passes too.
		specDoc["content_hash"] = "sha256:" + strings.Repeat("0", 64)
		for _, e := range runSchemaValidation(specDoc) {
			out.OK = false
			out.Errors = append(out.Errors, fieldErr{
				Field: schemaErrorField(e), Sev: "reject", Message: e.Error(),
			})
		}
		// Slug collision (warn only if same slug already in corpus and isn't us).
		if slug, _ := specDoc["slug"].(string); slug != "" {
			if existing, _ := findBySlug(corpus, slug); existing != nil {
				out.OK = false
				out.Errors = append(out.Errors, fieldErr{
					Field: "slug", Sev: "reject",
					Message: fmt.Sprintf("slug %q already exists at %s", slug, existing.Path),
				})
			}
		}
	}

	writeJSON(w, 200, out)
}

// handleDraftStage handles POST /api/drafts/primitives/{id}/stage. Equivalent
// to running create against the draft body, then deleting the draft on
// success. On failure the draft is preserved so the user can keep editing.
func (s *Server) handleDraftStage(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	env, err := s.readDraft(id)
	if err != nil {
		writeError(w, 500, err.Error())
		return
	}
	if env == nil {
		writeError(w, 404, "draft not found")
		return
	}
	res, status, err := s.writePrimitivePipeline(env.Body, opCreate, "")
	if err != nil {
		writeError(w, status, err.Error())
		return
	}
	// Promote: clean up the draft now that it's published.
	_ = os.Remove(s.draftPath(id))
	writeJSON(w, http.StatusCreated, res)
}

// schemaErrorField makes a best-effort field extraction from a validator
// error string. Falls back to "" when nothing parseable is in the message.
func schemaErrorField(e error) string {
	msg := e.Error()
	if i := strings.Index(msg, ":"); i > 0 {
		return strings.TrimSpace(msg[:i])
	}
	return ""
}

var _ = errors.Is // appease linters when no errors.Is calls remain post-refactor
